// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskTrackPro.Backend.DataAccess;

#nullable disable

namespace TaskTrackPro.Backend.DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250618202852_TablaRelacionUsuarioProyecto")]
    partial class TablaRelacionUsuarioProyecto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.Property<string>("ProyectoNombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProyectoNombre", "UsuarioEmail");

                    b.HasIndex("UsuarioEmail");

                    b.ToTable("ProyectoUsuario", (string)null);
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.Property<string>("TareasQueDependenDeMiTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TareasQueYoDependoTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TareasQueDependenDeMiTitulo", "TareasQueYoDependoTitulo");

                    b.HasIndex("TareasQueYoDependoTitulo");

                    b.ToTable("TareaTarea");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.Property<string>("Nombre")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministradorPEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Nombre");

                    b.HasIndex("AdministradorPEmail");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Tarea", b =>
                {
                    b.Property<string>("Titulo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProyectoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Titulo");

                    b.HasIndex("ProyectoNombre");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UsuarioTarea", b =>
                {
                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TareaTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UsuarioEmail", "TareaTitulo");

                    b.HasIndex("TareaTitulo");

                    b.ToTable("UsuarioTarea", (string)null);
                });

            modelBuilder.Entity("ProyectoUsuario", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Proyecto", null)
                        .WithMany()
                        .HasForeignKey("ProyectoNombre")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskTrackPro.Backend.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasQueDependenDeMiTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasQueYoDependoTitulo")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Usuario", "AdministradorP")
                        .WithMany()
                        .HasForeignKey("AdministradorPEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministradorP");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Tarea", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Proyecto", "Proyecto")
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("UsuarioTarea", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareaTitulo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskTrackPro.Backend.Dominio.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
