// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaskTrackPro.Backend.DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProyectoNombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TareaTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Email");

                    b.HasIndex("ProyectoNombre");

                    b.HasIndex("TareaTitulo");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.Property<string>("TareasQueDependenDeMiTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TareasQueYoDependoTitulo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TareasQueDependenDeMiTitulo", "TareasQueYoDependoTitulo");

                    b.HasIndex("TareasQueYoDependoTitulo");

                    b.ToTable("TareaTarea");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdministradorPEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Nombre");

                    b.HasIndex("AdministradorPEmail");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Tarea", b =>
                {
                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDeInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProyectoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Titulo");

                    b.HasIndex("ProyectoNombre");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("Dominio.Usuario", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Proyecto", null)
                        .WithMany("MiembrosProyecto")
                        .HasForeignKey("ProyectoNombre");

                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany("UsuariosAsignados")
                        .HasForeignKey("TareaTitulo");
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasQueDependenDeMiTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskTrackPro.Backend.Dominio.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasQueYoDependoTitulo")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.HasOne("Dominio.Usuario", "AdministradorP")
                        .WithMany()
                        .HasForeignKey("AdministradorPEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministradorP");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Tarea", b =>
                {
                    b.HasOne("TaskTrackPro.Backend.Dominio.Proyecto", null)
                        .WithMany("Tareas")
                        .HasForeignKey("ProyectoNombre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Proyecto", b =>
                {
                    b.Navigation("MiembrosProyecto");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("TaskTrackPro.Backend.Dominio.Tarea", b =>
                {
                    b.Navigation("UsuariosAsignados");
                });
#pragma warning restore 612, 618
        }
    }
}
