<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TaskTrackPro.Backend.Servicios</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
      <ProjectReference Include="..\Dominio\Dominio.csproj" />
      <ProjectReference Include="..\Dtos\Dtos.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    </ItemGroup>

</Project>
